# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dec828ee93bd0a13dd5e7cfc91e8ca52ec529d1dff00c017713b1e371e094ae95d74e6c2a1a5f727b2d3d502f9a8dc315326fc9cf202f85433f8ec977827671

test:
  secret_key_base: a22c324ac5d964cba9912c85f5078d24f019b2a3512c6e2e65f8d316bb5b4909ce7c554580720844ba79c9fd6d1d1b43919be2fb3a0d8af18381369b02722c90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
